import HautevilleHouse.WeylSumsCanonicalLaneLean.WeylSumExponentialSum
import HautevilleHouse.WeylSumsCanonicalLaneLean.Weyl_VanDerCorputLemma
import HautevilleHouse.WeylSumsCanonicalLaneLean.WeylDifferenceOperator
import HautevilleHouse.WeylSumsCanonicalLaneLean.WeylExponentialSumEstimates
import HautevilleHouse.WeylSumsCanonicalLaneLean.WeylFinalTheorem